# Generated by Django 5.0.14 on 2026-08-09 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("ngo_id", models.UUIDField(blank=True, null=True)),
                (
                    "predicted_demand_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("predicted_meals", models.IntegerField()),
                ("confidence_score", models.FloatField(default=0.85)),
                ("day_of_week", models.CharField(max_length=20)),
                ("target_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-target_date"],
            },
        ),
        migrations.AddField(
            model_name="impactmetric",
            name="water_saved_liters",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.CreateModel(
            name="PlatformReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation Activity Report"),
                            ("volunteer", "Volunteer Fleet Performance Report"),
                            ("ngo", "NGO Compliance & Claim Report"),
                            ("corporate", "Corporate CSR Compliance Report"),
                            ("csr", "ESG & Environmental Impact Audit"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("summary_data", models.JSONField(default=dict)),
                ("format", models.CharField(default="pdf", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
