# Generated by Django 5.0.14 on 2026-08-09 08:17

import common.gis
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngoprofile",
            name="registration_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="verification_document_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NGOFoodRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("food_category", models.CharField(max_length=100)),
                ("quantity_meals_needed", models.IntegerField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical / Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("location", common.gis.DummyPointField(blank=True, null=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_requests",
                        to="ngos.ngoprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
